name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  SOURCE_DIR: "source"

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Foreman dependencies
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: |
          selene generate-roblox-std
          selene ${{ env.SOURCE_DIR }}

      - name: Format
        run: stylua --check ${{ env.SOURCE_DIR }}
