name: Release

on:
  release:
    types: [published]

env:
  OUTPUT_NAME: "TestServiceWatcher.rbxm"
  ASSET_ID: 123456789

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: rojo build -o ${{ env.OUTPUT_NAME }}

      - name: Add model file to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.OUTPUT_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to asset library
        run: rojo upload --asset_id ${{ env.ASSET_ID }} --cookie "${{ secrets.ROBLOSECURITY }}"
